server:
  port: 9003 #端口
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kotlin?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: manager
    initialSize: 1  #初始化大小
    minIdle: 1  #空闲连接池的大小
    maxActive: 50 #最大激活数量
#MyBatis配置文件
mybatis:
  mapper-locations: classpath:mapper/*.xml